export const NIGERIAN_UNIVERSITIES = [
    "Abia State University (ABSU)",
    "Abubakar Tafawa Balewa University (ATBU)",
    "Achievers University, Owo",
    "Adamawa State University (ADSU)",
    "Adeyemi Federal University of Education, Ondo",
    "Afe Babalola University (ABUAD)",
    "Ahmadu Bello University (ABU)",
    "Air Force Institute of Technology (AFIT)",
    "Ajayi Crowther University",
    "Akwa Ibom State University (AKSU)",
    "Alex Ekwueme Federal University, Ndufu-Alike (AE-FUNAI)",
    "Ambrose Alli University (AAU)",
    "American University of Nigeria (AUN)",
    "Anchor University, Lagos",
    "Augustine University",
    "Babcock University",
    "Bauchi State University (BASUG)",
    "Bayero University Kano (BUK)",
    "Baze University",
    "Bells University of Technology",
    "Benue State University (BSU)",
    "Benson Idahosa University (BIU)",
    "Bingham University",
    "Bowen University",
    "Caleb University",
    "Chrisland University",
    "Chukwuemeka Odumegwu Ojukwu University (COOU)",
    "Covenant University",
    "Delta State University (DELSU)",
    "Ebonyi State University (EBSU)",
    "Edo State University, Uzairue",
    "Ekiti State University (EKSU)",
    "Elizade University",
    "Enugu State University of Science and Technology (ESUT)",
    "Federal University Birnin Kebbi (FUBK)",
    "Federal University Dutse (FUD)",
    "Federal University Dutsin-Ma (FUDMA)",
    "Federal University Gashua (FUGA)",
    "Federal University Gusau (FUGUS)",
    "Federal University Kashere (FUK)",
    "Federal University Lafia (FULafia)",
    "Federal University Lokoja (FUL)",
    "Federal University Of Agriculture, Abeokuta (FUNAAB)",
    "Federal University of Agriculture, Zuru",
    "Federal University of Health Sciences, Azare",
    "Federal University of Health Sciences, Otukpo (FUHSO)",
    "Federal University of Petroleum Resources, Effurun (FUPRE)",
    "Federal University of Technology Akure (FUTA)",
    "Federal University of Technology Minna (FUTMINNA)",
    "Federal University of Technology Owerri (FUTO)",
    "Federal University of Technology, Ikot-Abasi",
    "Federal University Otuoke (FUOtuoke)",
    "Federal University Oye-Ekiti (FUOYE)",
    "Federal University Wukari (FUW)",
    "Godfrey Okoye University",
    "Gombe State University (GSU)",
    "Gregory University, Uturu",
    "Ibrahim Badamasi Babangida University (IBBU)",
    "Ignatius Ajuru University of Education (IAUE)",
    "Igbinedion University, Okada",
    "Imo State University (IMSU)",
    "Joseph Sarwuan Tarka University (formerly FUAM)",
    "Kaduna State University (KASU)",
    "Kano University of Science and Technology (KUST)",
    "Kwara State University (KWASU)",
    "Ladoke Akintola University of Technology (LAUTECH)",
    "Lagos State University (LASU)",
    "Lagos State University of Education (LASUED)",
    "Lagos State University of Science and Technology (LASUSTECH)",
    "Landmark University",
    "Lead City University",
    "Madonna University",
    "McPherson University",
    "Michael Okpara University of Agriculture (MOUAU)",
    "Miva Open University",
    "Modibbo Adama University, Yola (MAU)",
    "Mountain Top University",
    "Nasarawa State University (NSUK)",
    "National Open University of Nigeria (NOUN)",
    "Niger Delta University (NDU)",
    "Nigerian Army University, Biu (NAUB)",
    "Nigerian Defence Academy (NDA)",
    "Nigerian Maritime University",
    "Nile University of Nigeria",
    "Nnamdi Azikiwe University (UNIZIK)",
    "Obafemi Awolowo University (OAU)",
    "Olabisi Onabanjo University (OOU)",
    "Osun State University (UNIOSUN)",
    "Pan-Atlantic University",
    "Redeemer's University",
    "Rivers State University (RSU)",
    "Tai Solarin University of Education (TASUED)",
    "Taraba State University (TASU)",
    "University of Abuja (UNIABUJA)",
    "University of Benin (UNIBEN)",
    "University of Calabar (UNICAL)",
    "University of Ibadan (UI)",
    "University of Ilorin (UNILORIN)",
    "University of Jos (UNIJOS)",
    "University of Lagos (UNILAG)",
    "University of Maiduguri (UNIMAID)",
    "University of Nigeria Nsukka (UNN)",
    "University of Port Harcourt (UNIPORT)",
    "University of Uyo (UNIUYO)",
    "Usmanu Danfodiyo University, Sokoto (UDUS)",
    "Veritas University, Abuja (VUNA)",
    "Wigwe University",
    "Yobe State University (YSU)"
].sort();

export const NIGERIAN_COURSES = [
    "Accounting",
    "Aerospace Engineering",
    "Agricultural Economics",
    "Agricultural Engineering",
    "Agricultural Extension",
    "Anatomy",
    "Animal Science",
    "Architecture",
    "Banking and Finance",
    "Biochemistry",
    "Biology",
    "Biomedical Engineering",
    "Biotechnology",
    "Botany",
    "Building Technology",
    "Business Administration",
    "Chemical Engineering",
    "Chemistry",
    "Christian Religious Studies",
    "Civil Engineering",
    "Computer Engineering",
    "Computer Science",
    "Creative Arts",
    "Criminology and Security Studies",
    "Crop Science",
    "Dentistry",
    "Economics",
    "Education and Biology",
    "Education and Chemistry",
    "Education and Computer Science",
    "Education and Economics",
    "Education and English",
    "Education and Mathematics",
    "Education and Physics",
    "Educational Management",
    "Electrical/Electronic Engineering",
    "English Language and Literature",
    "Entrepreneurship",
    "Environmental Science",
    "Estate Management",
    "Fine and Applied Arts",
    "Fisheries and Aquaculture",
    "Food Science and Technology",
    "Forestry and Wildlife Management",
    "French",
    "Geography",
    "Geology",
    "Guidance and Counselling",
    "History and International Studies",
    "Human Physiology",
    "Human Resource Management",
    "Industrial and Production Engineering",
    "Industrial Chemistry",
    "Information and Communication Technology",
    "Insurance",
    "International Relations",
    "Islamic Studies",
    "Law (LL.B)",
    "Library and Information Science",
    "Linguistics",
    "Marine Science",
    "Marketing",
    "Mass Communication",
    "Mathematics",
    "Mechanical Engineering",
    "Mechatronics Engineering",
    "Medical Laboratory Science",
    "Medicine and Surgery (MBBS)",
    "Metallurgical and Materials Engineering",
    "Microbiology",
    "Music",
    "Nursing Science",
    "Optometry",
    "Peace and Conflict Studies",
    "Petroleum Engineering",
    "Pharmacy",
    "Philosophy",
    "Physics",
    "Physiotherapy",
    "Political Science",
    "Psychology",
    "Public Administration",
    "Public Health",
    "Quantity Surveying",
    "Radiography",
    "Social Work",
    "Sociology",
    "Software Engineering",
    "Statistics",
    "Surveying and Geoinformatics",
    "Systems Engineering",
    "Telecommunications Engineering",
    "Theatre and Film Studies",
    "Tourism and Hospitality Management",
    "Urban and Regional Planning",
    "Veterinary Medicine",
    "Zoology"
].sort();
